/* =====================================================
   EDUQUEST BACHILLERATO — data.js
   Banco de Preguntas (5 Materias, 4 Tipos de Juego)
   ===================================================== */

const EQ_DATA = {

  /* ─── MATERIAS ─── */
  subjects: {
    matematica: {
      id: 'matematica',
      name: 'Matemática',
      icon: '🔢',
      color: '#2563EB',
      gradient: 'linear-gradient(135deg, #1D4ED8, #7C3AED)',
      desc: 'Álgebra, geometría, funciones, estadística y cálculo aplicado al bachillerato.',
      xpPerQ: 20,
    },
    lengua: {
      id: 'lengua',
      name: 'Lengua y Literatura',
      icon: '📚',
      color: '#7C3AED',
      gradient: 'linear-gradient(135deg, #7C3AED, #EC4899)',
      desc: 'Gramática, ortografía, análisis literario y tipos de texto.',
      xpPerQ: 20,
    },
    fisica: {
      id: 'fisica',
      name: 'Física',
      icon: '⚡',
      color: '#F59E0B',
      gradient: 'linear-gradient(135deg, #D97706, #F59E0B)',
      desc: 'Cinemática, dinámica, energía, ondas y electromagnetismo.',
      xpPerQ: 25,
    },
    quimica: {
      id: 'quimica',
      name: 'Química',
      icon: '⚗️',
      color: '#10B981',
      gradient: 'linear-gradient(135deg, #059669, #10B981)',
      desc: 'Tabla periódica, reacciones químicas, estequiometría y enlaces.',
      xpPerQ: 25,
    },
    biologia: {
      id: 'biologia',
      name: 'Biología',
      icon: '🧬',
      color: '#EF4444',
      gradient: 'linear-gradient(135deg, #DC2626, #EF4444)',
      desc: 'Célula, genética, ecosistemas y anatomía humana.',
      xpPerQ: 20,
    },
  },

  /* ─── PREGUNTAS ─── */
  questions: {

    /* ════════════════════ MATEMÁTICA ════════════════════ */
    matematica: [
      // Quiz opción múltiple
      { id: 'm1', type: 'quiz', difficulty: 1,
        q: '¿Cuánto es 2³ + 3²?',
        options: ['15', '17', '19', '13'],
        answer: 1, explanation: '2³ = 8 y 3² = 9, entonces 8 + 9 = 17.' },
      { id: 'm2', type: 'quiz', difficulty: 1,
        q: 'Si f(x) = 3x + 5, ¿cuál es f(4)?',
        options: ['15', '17', '12', '20'],
        answer: 1, explanation: 'f(4) = 3(4) + 5 = 12 + 5 = 17.' },
      { id: 'm3', type: 'quiz', difficulty: 2,
        q: '¿Cuál es la solución de la ecuación 2x - 6 = 10?',
        options: ['x = 4', 'x = 8', 'x = 2', 'x = 6'],
        answer: 1, explanation: '2x = 16, por lo tanto x = 8.' },
      { id: 'm4', type: 'quiz', difficulty: 2,
        q: '¿Cuál es el área de un triángulo con base 8 cm y altura 5 cm?',
        options: ['40 cm²', '20 cm²', '13 cm²', '80 cm²'],
        answer: 1, explanation: 'Área = (base × altura)/2 = (8×5)/2 = 20 cm².' },
      { id: 'm5', type: 'quiz', difficulty: 2,
        q: '¿Cuánto es √144?',
        options: ['11', '12', '13', '14'],
        answer: 1, explanation: '12 × 12 = 144, entonces √144 = 12.' },
      { id: 'm6', type: 'quiz', difficulty: 3,
        q: 'Si log₂(x) = 5, ¿cuál es el valor de x?',
        options: ['10', '25', '32', '64'],
        answer: 2, explanation: 'log₂(x) = 5 significa 2⁵ = x = 32.' },
      { id: 'm7', type: 'quiz', difficulty: 3,
        q: '¿Cuál es la derivada de f(x) = x³ - 4x?',
        options: ['3x² - 4', '3x² + 4', 'x² - 4', '3x - 4'],
        answer: 0, explanation: 'f\'(x) = 3x² - 4.' },
      // Verdadero o Falso
      { id: 'm8', type: 'tf', difficulty: 1,
        q: 'El número π es exactamente igual a 3.14.',
        answer: false, explanation: 'π es irracional: 3.14159265…, no es exactamente 3.14.' },
      { id: 'm9', type: 'tf', difficulty: 1,
        q: 'La suma de los ángulos interiores de un triángulo es 180°.',
        answer: true, explanation: 'Correcto. Es un postulado fundamental de la geometría euclidiana.' },
      { id: 'm10', type: 'tf', difficulty: 2,
        q: 'Todo número primo es impar.',
        answer: false, explanation: 'El 2 es primo y es par.' },
      { id: 'm11', type: 'tf', difficulty: 2,
        q: 'La media aritmética de {2, 4, 6, 8} es 5.',
        answer: true, explanation: '(2+4+6+8)/4 = 20/4 = 5.' },
      // Completar palabras
      { id: 'm12', type: 'fill', difficulty: 1,
        q: 'El Teorema de Pitágoras dice: a² + b² = ___',
        answer: 'c²', hint: 'La hipotenusa al cuadrado', explanation: 'a² + b² = c², donde c es la hipotenusa.' },
      { id: 'm13', type: 'fill', difficulty: 2,
        q: 'La fórmula del perímetro de un círculo es P = 2 × π × ___',
        answer: 'r', hint: 'La distancia del centro al borde', explanation: 'P = 2πr, donde r es el radio.' },
      { id: 'm14', type: 'fill', difficulty: 2,
        q: 'En una progresión aritmética, la diferencia entre términos consecutivos se llama ___',
        answer: 'razón', hint: 'La letra "r" en la fórmula', explanation: 'La razón (d o r) es la diferencia constante.' },
      // Asociación
      { id: 'm15', type: 'match', difficulty: 1,
        q: 'Asocia cada figura con su fórmula de área:',
        pairs: [
          { left: 'Cuadrado', right: 'l²' },
          { left: 'Círculo', right: 'πr²' },
          { left: 'Rectángulo', right: 'b × h' },
          { left: 'Triángulo', right: 'b × h / 2' },
        ]},
      { id: 'm16', type: 'quiz', difficulty: 3,
        q: 'Si un auto viaja a 60 km/h, ¿cuánto tiempo tarda en recorrer 150 km?',
        options: ['2 h', '2.5 h', '3 h', '2.25 h'],
        answer: 1, explanation: 't = d/v = 150/60 = 2.5 horas.' },
      { id: 'm17', type: 'quiz', difficulty: 2,
        q: '¿Cuál es el mínimo común múltiplo de 4 y 6?',
        options: ['12', '24', '6', '8'],
        answer: 0, explanation: 'MCM(4,6) = 12.' },
      { id: 'm18', type: 'tf', difficulty: 3,
        q: 'La función y = x² es siempre creciente.',
        answer: false, explanation: 'Solo es creciente para x > 0; para x < 0 es decreciente.' },
      { id: 'm19', type: 'fill', difficulty: 3,
        q: 'La fórmula general para resolver ecuaciones cuadráticas ax²+bx+c=0 usa el ___',
        answer: 'discriminante', hint: 'b²-4ac', explanation: 'El discriminante b²-4ac determina la naturaleza de las raíces.' },
      { id: 'm20', type: 'quiz', difficulty: 1,
        q: '¿Cuánto es 15% de 200?',
        options: ['25', '30', '35', '20'],
        answer: 1, explanation: '15% × 200 = 0.15 × 200 = 30.' },
    ],

    /* ════════════════════ LENGUA Y LITERATURA ════════════════════ */
    lengua: [
      { id: 'l1', type: 'quiz', difficulty: 1,
        q: '¿Cuál de estas palabras tiene tilde correctamente colocada?',
        options: ['examen', 'canción', 'futbol', 'cafe'],
        answer: 1, explanation: '"Canción" lleva tilde porque es aguda terminada en -n.' },
      { id: 'l2', type: 'quiz', difficulty: 1,
        q: 'El sujeto de la oración "Los estudiantes leen libros" es:',
        options: ['leen', 'libros', 'Los estudiantes', 'Los'],
        answer: 2, explanation: '"Los estudiantes" realiza la acción de leer.' },
      { id: 'l3', type: 'quiz', difficulty: 2,
        q: '¿Qué figura retórica usa "el tiempo es oro"?',
        options: ['Metáfora', 'Símil', 'Hipérbole', 'Ironía'],
        answer: 0, explanation: 'Es una metáfora: identifica tiempo con oro sin usar "como".' },
      { id: 'l4', type: 'quiz', difficulty: 2,
        q: '¿Cuál es el narrador en primera persona?',
        options: ['Omnisciente', 'Protagonista', 'Testigo externo', 'Objetivo'],
        answer: 1, explanation: 'El narrador protagonista usa "yo" y cuenta su propia historia.' },
      { id: 'l5', type: 'quiz', difficulty: 3,
        q: '"Don Quijote de la Mancha" fue escrito por:',
        options: ['Lope de Vega', 'Miguel de Cervantes', 'Francisco de Quevedo', 'Tirso de Molina'],
        answer: 1, explanation: 'Miguel de Cervantes publicó la obra en 1605 y 1615.' },
      { id: 'l6', type: 'tf', difficulty: 1,
        q: 'La palabra "televisión" es un sustantivo.',
        answer: true, explanation: 'Es un sustantivo que nombra un objeto.' },
      { id: 'l7', type: 'tf', difficulty: 2,
        q: 'Los adverbios modifican solo a verbos.',
        answer: false, explanation: 'Los adverbios modifican verbos, adjetivos y otros adverbios.' },
      { id: 'l8', type: 'tf', difficulty: 1,
        q: 'El punto y coma (;) indica una pausa menor que la coma.',
        answer: false, explanation: 'El punto y coma indica una pausa mayor que la coma pero menor que el punto.' },
      { id: 'l9', type: 'tf', difficulty: 2,
        q: 'El cuento y la novela son subgéneros del género narrativo.',
        answer: true, explanation: 'Ambos pertenecen al género narrativo o épico.' },
      { id: 'l10', type: 'fill', difficulty: 1,
        q: 'La figura retórica que consiste en la repetición de sonidos consonánticos se llama ___',
        answer: 'aliteración', hint: 'Ej: "tres tristes tigres"', explanation: 'La aliteración repite sonidos para crear efecto sonoro.' },
      { id: 'l11', type: 'fill', difficulty: 2,
        q: 'El género literario que se escribe en verso y expresa sentimientos se llama género ___',
        answer: 'lírico', hint: 'Poesía', explanation: 'El género lírico o poético expresa emociones y sentimientos.' },
      { id: 'l12', type: 'fill', difficulty: 2,
        q: 'La parte de la oración que une palabras u oraciones se llama ___',
        answer: 'conjunción', hint: 'Ej: y, pero, porque', explanation: 'Las conjunciones son nexos gramaticales.' },
      { id: 'l13', type: 'match', difficulty: 2,
        q: 'Asocia el recurso literario con su ejemplo:',
        pairs: [
          { left: 'Metáfora', right: 'La vida es un sueño' },
          { left: 'Símil', right: 'Corre como el viento' },
          { left: 'Hipérbole', right: 'Te lo dije mil veces' },
          { left: 'Personificación', right: 'El sol sonríe' },
        ]},
      { id: 'l14', type: 'quiz', difficulty: 2,
        q: '¿Qué tipo de texto presenta argumentos para persuadir al lector?',
        options: ['Descriptivo', 'Narrativo', 'Argumentativo', 'Expositivo'],
        answer: 2, explanation: 'El texto argumentativo busca convencer mediante razonamientos.' },
      { id: 'l15', type: 'quiz', difficulty: 3,
        q: '¿Cuál es la función del lenguaje cuando decimos "¡Qué bonito día!"?',
        options: ['Referencial', 'Emotiva', 'Fática', 'Metalingüística'],
        answer: 1, explanation: 'La función emotiva expresa sentimientos del emisor.' },
      { id: 'l16', type: 'tf', difficulty: 3,
        q: '"Cien años de soledad" es una obra del realismo mágico latinoamericano.',
        answer: true, explanation: 'García Márquez es el máximo exponente del realismo mágico.' },
      { id: 'l17', type: 'fill', difficulty: 3,
        q: 'El recurso literario que consiste en dar cualidades humanas a objetos inanimados es la ___',
        answer: 'personificación', hint: 'También llamada prosopopeya', explanation: 'La personificación o prosopopeya atribuye características humanas a seres no humanos.' },
      { id: 'l18', type: 'quiz', difficulty: 1,
        q: '¿Cuál es el antónimo de "frío"?',
        options: ['Tibio', 'Helado', 'Cálido', 'Fresco'],
        answer: 2, explanation: 'Cálido/caliente es el antónimo de frío.' },
      { id: 'l19', type: 'quiz', difficulty: 2,
        q: 'En la estructura del cuento, ¿qué elemento presenta el conflicto principal?',
        options: ['Exposición', 'Nudo', 'Desenlace', 'Clímax'],
        answer: 1, explanation: 'El nudo es donde se desarrolla y complica el conflicto.' },
      { id: 'l20', type: 'tf', difficulty: 2,
        q: 'La palabra "psicología" se puede escribir con "s" inicial en lugar de "ps".',
        answer: true, explanation: 'En español moderno se acepta "sicología" y variantes sin la "p" inicial.' },
    ],

    /* ════════════════════ FÍSICA ════════════════════ */
    fisica: [
      { id: 'f1', type: 'quiz', difficulty: 1,
        q: '¿Cuál es la unidad del SI para medir fuerza?',
        options: ['Pascal', 'Newton', 'Joule', 'Watt'],
        answer: 1, explanation: 'La fuerza se mide en Newtons (N) en el Sistema Internacional.' },
      { id: 'f2', type: 'quiz', difficulty: 1,
        q: 'La velocidad de la luz en el vacío es aproximadamente:',
        options: ['300 000 km/s', '150 000 km/s', '3 000 km/s', '30 000 km/s'],
        answer: 0, explanation: 'c ≈ 300 000 km/s = 3×10⁸ m/s.' },
      { id: 'f3', type: 'quiz', difficulty: 2,
        q: 'La Primera Ley de Newton es conocida como la ley de:',
        options: ['Acción y reacción', 'Gravedad', 'Inercia', 'Aceleración'],
        answer: 2, explanation: 'La 1ª Ley dice que un cuerpo en reposo permanece en reposo (inercia).' },
      { id: 'f4', type: 'quiz', difficulty: 2,
        q: 'Un objeto cae libremente desde el reposo. ¿Qué velocidad alcanza tras 3 segundos? (g=10 m/s²)',
        options: ['10 m/s', '20 m/s', '30 m/s', '40 m/s'],
        answer: 2, explanation: 'v = g×t = 10 × 3 = 30 m/s.' },
      { id: 'f5', type: 'quiz', difficulty: 3,
        q: 'La fórmula del trabajo mecánico es:',
        options: ['W = m×g', 'W = F×d×cos(θ)', 'W = P×V', 'W = ½mv²'],
        answer: 1, explanation: 'W = F × d × cos(θ), donde θ es el ángulo entre la fuerza y el desplazamiento.' },
      { id: 'f6', type: 'tf', difficulty: 1,
        q: 'La masa y el peso de un objeto son la misma magnitud física.',
        answer: false, explanation: 'Masa es kg (cantidad de materia); Peso es N (fuerza gravitatoria).' },
      { id: 'f7', type: 'tf', difficulty: 2,
        q: 'La energía cinética de un objeto depende de su velocidad al cuadrado.',
        answer: true, explanation: 'Ec = ½mv², por lo que depende de v².' },
      { id: 'f8', type: 'tf', difficulty: 2,
        q: 'La temperatura del cero absoluto es -273.15°C.',
        answer: true, explanation: '0 K = -273.15°C. Es el límite inferior de temperatura.' },
      { id: 'f9', type: 'fill', difficulty: 1,
        q: 'La fórmula de la velocidad es v = ___ / tiempo',
        answer: 'distancia', hint: 'Lo que recorre el objeto', explanation: 'v = d/t. Velocidad = distancia / tiempo.' },
      { id: 'f10', type: 'fill', difficulty: 2,
        q: 'La Segunda Ley de Newton establece que F = m × ___',
        answer: 'a', hint: 'La variación de velocidad', explanation: 'F = m × a (masa por aceleración).' },
      { id: 'f11', type: 'fill', difficulty: 3,
        q: 'La unidad de medida de la presión en el SI es el ___',
        answer: 'Pascal', hint: 'Pa = N/m²', explanation: 'El Pascal (Pa) = 1 Newton por metro cuadrado.' },
      { id: 'f12', type: 'match', difficulty: 2,
        q: 'Asocia la ley con su enunciado:',
        pairs: [
          { left: '1ª Ley Newton', right: 'Inercia' },
          { left: '2ª Ley Newton', right: 'F = ma' },
          { left: '3ª Ley Newton', right: 'Acción y reacción' },
          { left: 'Ley de Hooke', right: 'F = -kx' },
        ]},
      { id: 'f13', type: 'quiz', difficulty: 2,
        q: '¿Cuál es la unidad de potencia en el SI?',
        options: ['Newton', 'Joule', 'Watt', 'Pascal'],
        answer: 2, explanation: 'La potencia se mide en Watts (W). 1 W = 1 J/s.' },
      { id: 'f14', type: 'quiz', difficulty: 3,
        q: 'Si P = 800 W y t = 5 s, ¿cuánta energía se transforma?',
        options: ['160 J', '4000 J', '805 J', '160 kJ'],
        answer: 1, explanation: 'E = P × t = 800 × 5 = 4000 J.' },
      { id: 'f15', type: 'tf', difficulty: 3,
        q: 'Las ondas sonoras son ondas transversales.',
        answer: false, explanation: 'El sonido es una onda longitudinal (oscila en la misma dirección de propagación).' },
      { id: 'f16', type: 'quiz', difficulty: 1,
        q: '¿Qué instrumento mide la temperatura?',
        options: ['Barómetro', 'Termómetro', 'Higrómetro', 'Anemómetro'],
        answer: 1, explanation: 'El termómetro es el instrumento para medir temperatura.' },
      { id: 'f17', type: 'fill', difficulty: 2,
        q: 'La fórmula de la energía potencial gravitatoria es Ep = m × g × ___',
        answer: 'h', hint: 'Altura del objeto', explanation: 'Ep = mgh, donde h es la altura.' },
      { id: 'f18', type: 'quiz', difficulty: 2,
        q: '¿Qué tipo de lente es divergente?',
        options: ['Convexa', 'Biconvexa', 'Cóncava', 'Plano-convexa'],
        answer: 2, explanation: 'Las lentes cóncavas son divergentes: separan los rayos de luz.' },
      { id: 'f19', type: 'tf', difficulty: 1,
        q: 'La electricidad estática ocurre por transferencia de electrones.',
        answer: true, explanation: 'La carga eléctrica estática se debe al exceso o déficit de electrones.' },
      { id: 'f20', type: 'quiz', difficulty: 3,
        q: 'La ley de Ohm establece que la corriente es:',
        options: ['I = V × R', 'I = V / R', 'I = R / V', 'I = V + R'],
        answer: 1, explanation: 'I = V/R (corriente = voltaje / resistencia).' },
    ],

    /* ════════════════════ QUÍMICA ════════════════════ */
    quimica: [
      { id: 'q1', type: 'quiz', difficulty: 1,
        q: '¿Cuál es el símbolo químico del oro?',
        options: ['Go', 'Or', 'Au', 'Ag'],
        answer: 2, explanation: 'Au (del latín "aurum") es el símbolo del oro.' },
      { id: 'q2', type: 'quiz', difficulty: 1,
        q: '¿Cuántos elementos tiene la tabla periódica actual?',
        options: ['108', '112', '118', '120'],
        answer: 2, explanation: 'La tabla periódica actual tiene 118 elementos confirmados.' },
      { id: 'q3', type: 'quiz', difficulty: 2,
        q: 'El agua (H₂O) contiene:',
        options: ['2 átomos de oxígeno y 1 de hidrógeno', '1 átomo de oxígeno y 2 de hidrógeno', '2 de hidrógeno y 2 de oxígeno', '3 átomos de oxígeno'],
        answer: 1, explanation: 'H₂O = 2 hidrógenos + 1 oxígeno por molécula.' },
      { id: 'q4', type: 'quiz', difficulty: 2,
        q: 'El número atómico del carbono (C) es:',
        options: ['4', '6', '8', '12'],
        answer: 1, explanation: 'El carbono tiene número atómico 6 (6 protones).' },
      { id: 'q5', type: 'quiz', difficulty: 3,
        q: 'En la reacción CH₄ + 2O₂ → CO₂ + 2H₂O, el CH₄ es:',
        options: ['Oxidante', 'Catalizador', 'Combustible (reductor)', 'Producto'],
        answer: 2, explanation: 'El metano (CH₄) se oxida; es el combustible/reductor.' },
      { id: 'q6', type: 'tf', difficulty: 1,
        q: 'Los metales se ubican en el lado derecho de la tabla periódica.',
        answer: false, explanation: 'Los metales están principalmente en el lado izquierdo y centro.' },
      { id: 'q7', type: 'tf', difficulty: 1,
        q: 'El pH de una solución neutra es 7.',
        answer: true, explanation: 'pH 7 = neutro. pH < 7 = ácido; pH > 7 = básico.' },
      { id: 'q8', type: 'tf', difficulty: 2,
        q: 'Los enlaces iónicos se forman entre dos no metales.',
        answer: false, explanation: 'Los iónicos se forman entre metal y no-metal. Entre dos no-metales es enlace covalente.' },
      { id: 'q9', type: 'tf', difficulty: 3,
        q: 'La ley de conservación de la materia establece que la masa total de los reactivos es igual a la de los productos.',
        answer: true, explanation: 'Ley de Lavoisier: "La materia no se crea ni se destruye, solo se transforma".' },
      { id: 'q10', type: 'fill', difficulty: 1,
        q: 'El símbolo químico del sodio es ___',
        answer: 'Na', hint: 'Del latín "Natrium"', explanation: 'Na proviene de "Natrium" en latín.' },
      { id: 'q11', type: 'fill', difficulty: 2,
        q: 'La capa más externa del átomo que contiene los electrones de valencia se llama ___',
        answer: 'capa de valencia', hint: 'Última capa electrónica', explanation: 'La capa de valencia determina la reactividad del elemento.' },
      { id: 'q12', type: 'fill', difficulty: 2,
        q: 'El proceso por el cual una sustancia pasa de estado sólido a gaseoso sin pasar por líquido se llama ___',
        answer: 'sublimación', hint: 'El hielo seco lo hace', explanation: 'La sublimación: sólido → gas directamente (ej: CO₂ sólido).' },
      { id: 'q13', type: 'match', difficulty: 2,
        q: 'Asocia el elemento con su símbolo:',
        pairs: [
          { left: 'Hierro', right: 'Fe' },
          { left: 'Plata', right: 'Ag' },
          { left: 'Potasio', right: 'K' },
          { left: 'Mercurio', right: 'Hg' },
        ]},
      { id: 'q14', type: 'quiz', difficulty: 2,
        q: '¿Cuál de estas es una mezcla homogénea?',
        options: ['Agua con arena', 'Agua con aceite', 'Agua con sal', 'Agua con tierra'],
        answer: 2, explanation: 'El agua con sal es una solución (mezcla homogénea).' },
      { id: 'q15', type: 'quiz', difficulty: 3,
        q: 'La estequiometría estudia las _____ de las reacciones químicas.',
        options: ['Velocidades', 'Proporciones y cantidades', 'Energías', 'Temperaturas'],
        answer: 1, explanation: 'La estequiometría analiza las proporciones de reactivos y productos.' },
      { id: 'q16', type: 'quiz', difficulty: 1,
        q: '¿Cuál de estas es una propiedad física?',
        options: ['Combustión', 'Oxidación', 'Densidad', 'Fermentación'],
        answer: 2, explanation: 'La densidad es una propiedad física (no altera la composición).' },
      { id: 'q17', type: 'tf', difficulty: 2,
        q: 'El hidrógeno es el elemento más abundante en el universo.',
        answer: true, explanation: 'El hidrógeno representa ~75% de toda la materia visible del universo.' },
      { id: 'q18', type: 'fill', difficulty: 3,
        q: 'La escala de pH va del 0 al ___',
        answer: '14', hint: 'El valor máximo básico', explanation: 'La escala de pH va de 0 (muy ácido) a 14 (muy básico).' },
      { id: 'q19', type: 'quiz', difficulty: 2,
        q: '¿Qué tipo de enlace forma el NaCl (sal de mesa)?',
        options: ['Covalente', 'Metálico', 'Iónico', 'Van der Waals'],
        answer: 2, explanation: 'NaCl: Na (metal) + Cl (no-metal) = enlace iónico.' },
      { id: 'q20', type: 'quiz', difficulty: 3,
        q: 'En la electrólisis del agua, en el cátodo se produce:',
        options: ['Oxígeno', 'Cloro', 'Hidrógeno', 'Vapor de agua'],
        answer: 2, explanation: 'En el cátodo (polo negativo) se reduce el H⁺ formando H₂.' },
    ],

    /* ════════════════════ BIOLOGÍA ════════════════════ */
    biologia: [
      { id: 'b1', type: 'quiz', difficulty: 1,
        q: '¿Cuál es la unidad estructural y funcional de los seres vivos?',
        options: ['El tejido', 'El órgano', 'La célula', 'El sistema'],
        answer: 2, explanation: 'La célula es la unidad básica de todos los seres vivos.' },
      { id: 'b2', type: 'quiz', difficulty: 1,
        q: 'El ADN se encuentra principalmente en:',
        options: ['La mitocondria', 'El citoplasma', 'El núcleo celular', 'El ribosoma'],
        answer: 2, explanation: 'El ADN nuclear se ubica en el núcleo de la célula.' },
      { id: 'b3', type: 'quiz', difficulty: 2,
        q: 'La fotosíntesis ocurre en:',
        options: ['Mitocondrias', 'Cloroplastos', 'Ribosomas', 'Vacuolas'],
        answer: 1, explanation: 'Los cloroplastos contienen la clorofila y realizan la fotosíntesis.' },
      { id: 'b4', type: 'quiz', difficulty: 2,
        q: '¿Cuántos pares de cromosomas tiene la célula humana normal?',
        options: ['23', '22', '24', '46'],
        answer: 0, explanation: 'Los humanos tienen 23 pares de cromosomas (46 en total).' },
      { id: 'b5', type: 'quiz', difficulty: 3,
        q: 'La meiosis produce:',
        options: ['2 células diploides', '4 células diploides', '4 células haploides', '2 células haploides'],
        answer: 2, explanation: 'La meiosis produce 4 células haploides (con la mitad de cromosomas).' },
      { id: 'b6', type: 'tf', difficulty: 1,
        q: 'Las bacterias son organismos eucariotas.',
        answer: false, explanation: 'Las bacterias son procariotas: no tienen núcleo definido.' },
      { id: 'b7', type: 'tf', difficulty: 1,
        q: 'El corazón humano tiene 4 cámaras.',
        answer: true, explanation: 'Aurícula derecha, aurícula izquierda, ventrículo derecho y ventrículo izquierdo.' },
      { id: 'b8', type: 'tf', difficulty: 2,
        q: 'Los productores de un ecosistema son los animales.',
        answer: false, explanation: 'Los productores son las plantas y algas que realizan fotosíntesis.' },
      { id: 'b9', type: 'tf', difficulty: 2,
        q: 'La insulina es una hormona producida por el páncreas.',
        answer: true, explanation: 'Las células beta del páncreas secretan insulina para regular la glucosa.' },
      { id: 'b10', type: 'fill', difficulty: 1,
        q: 'El proceso por el cual las células obtienen energía de la glucosa se llama ___',
        answer: 'respiración celular', hint: 'Ocurre en la mitocondria', explanation: 'La respiración celular aeróbica produce ATP en la mitocondria.' },
      { id: 'b11', type: 'fill', difficulty: 2,
        q: 'La molécula que transporta la información genética desde el ADN hasta los ribosomas es el ___',
        answer: 'ARN mensajero', hint: 'ARNm', explanation: 'El ARN mensajero (ARNm) lleva el código genético al ribosoma.' },
      { id: 'b12', type: 'fill', difficulty: 2,
        q: 'El proceso por el cual una célula se divide en dos células hijas idénticas se llama ___',
        answer: 'mitosis', hint: 'División celular somática', explanation: 'La mitosis produce células hijas genéticamente idénticas.' },
      { id: 'b13', type: 'match', difficulty: 2,
        q: 'Asocia el orgánulo con su función:',
        pairs: [
          { left: 'Mitocondria', right: 'Energía (ATP)' },
          { left: 'Ribosoma', right: 'Síntesis de proteínas' },
          { left: 'Cloroplasto', right: 'Fotosíntesis' },
          { left: 'Vacuola', right: 'Almacenamiento' },
        ]},
      { id: 'b14', type: 'quiz', difficulty: 2,
        q: '¿Qué tipo de simbiosis ocurre cuando un organismo se beneficia y el otro no es afectado?',
        options: ['Mutualismo', 'Parasitismo', 'Comensalismo', 'Depredación'],
        answer: 2, explanation: 'Comensalismo: uno se beneficia, el otro ni se beneficia ni se perjudica.' },
      { id: 'b15', type: 'quiz', difficulty: 3,
        q: 'La teoría de la evolución por selección natural fue propuesta por:',
        options: ['Gregor Mendel', 'Louis Pasteur', 'Charles Darwin', 'Alexander Fleming'],
        answer: 2, explanation: 'Darwin publicó "El origen de las especies" en 1859.' },
      { id: 'b16', type: 'quiz', difficulty: 1,
        q: '¿Cuál es el órgano del sistema nervioso central que controla las funciones vitales?',
        options: ['Cerebelo', 'Bulbo raquídeo', 'Cerebro', 'Médula espinal'],
        answer: 1, explanation: 'El bulbo raquídeo controla respiración, ritmo cardíaco y otras funciones vitales.' },
      { id: 'b17', type: 'tf', difficulty: 3,
        q: 'El ADN es una molécula de doble hélice formada por nucleótidos.',
        answer: true, explanation: 'Watson y Crick describieron la doble hélice del ADN en 1953.' },
      { id: 'b18', type: 'fill', difficulty: 3,
        q: 'El científico que es considerado el padre de la genética es ___',
        answer: 'Gregor Mendel', hint: 'Trabajó con guisantes', explanation: 'Gregor Mendel descubrió las leyes de la herencia con experimentos en guisantes.' },
      { id: 'b19', type: 'quiz', difficulty: 2,
        q: '¿Cuál es la función principal de los glóbulos rojos?',
        options: ['Combatir infecciones', 'Transportar oxígeno', 'Coagular la sangre', 'Producir anticuerpos'],
        answer: 1, explanation: 'Los eritrocitos (glóbulos rojos) transportan O₂ mediante la hemoglobina.' },
      { id: 'b20', type: 'quiz', difficulty: 3,
        q: 'El proceso de transcripción consiste en:',
        options: ['ADN → Proteína', 'ARN → ADN', 'ADN → ARN', 'ARN → Proteína'],
        answer: 2, explanation: 'La transcripción copia la información del ADN al ARNm.' },
    ],
  },

  /* ─── NIVELES ─── */
  levels: [
    { level: 1, name: 'Novato',          minXP: 0,     icon: '🌱' },
    { level: 2, name: 'Aprendiz',        minXP: 200,   icon: '📖' },
    { level: 3, name: 'Explorador',      minXP: 500,   icon: '🔭' },
    { level: 4, name: 'Aventurero',      minXP: 1000,  icon: '⚔️' },
    { level: 5, name: 'Experto',         minXP: 2000,  icon: '🎯' },
    { level: 6, name: 'Maestro',         minXP: 4000,  icon: '🏆' },
    { level: 7, name: 'Gran Maestro',    minXP: 7500,  icon: '👑' },
    { level: 8, name: 'Leyenda EduQuest',minXP: 12000, icon: '⭐' },
  ],

  /* ─── LOGROS ─── */
  achievements: [
    {
      id: 'first_quiz',
      name: 'Primera Victoria',
      desc: 'Completa tu primer quiz',
      icon: '🏆',
      condition: (stats) => stats.totalQuizzes >= 1,
    },
    {
      id: 'streak_7',
      name: 'En Racha 🔥',
      desc: '7 días consecutivos de práctica',
      icon: '🔥',
      condition: (stats) => stats.streak >= 7,
    },
    {
      id: 'math_expert',
      name: 'Matemático Experto',
      desc: 'Acumula 500 XP en Matemática',
      icon: '🧮',
      condition: (stats) => (stats.xpBySubject?.matematica || 0) >= 500,
    },
    {
      id: 'lengua_master',
      name: 'Maestro de Lengua',
      desc: 'Acumula 500 XP en Lengua y Literatura',
      icon: '📚',
      condition: (stats) => (stats.xpBySubject?.lengua || 0) >= 500,
    },
    {
      id: 'scientist',
      name: 'Científico Destacado',
      desc: 'Completa 10 quizzes entre Física, Química y Biología',
      icon: '⚗️',
      condition: (stats) => ((stats.quizzesBySubject?.fisica || 0) + (stats.quizzesBySubject?.quimica || 0) + (stats.quizzesBySubject?.biologia || 0)) >= 10,
    },
    {
      id: 'legend',
      name: 'Leyenda EduQuest',
      desc: 'Alcanza el nivel máximo (Nivel 8)',
      icon: '👑',
      condition: (stats) => stats.level >= 8,
    },
    {
      id: 'speedster',
      name: 'Velocista ⚡',
      desc: 'Responde 10 preguntas correctas con menos de 5s restantes',
      icon: '⚡',
      condition: (stats) => (stats.fastCorrect || 0) >= 10,
    },
    {
      id: 'perfectionist',
      name: 'Perfeccionista 🎯',
      desc: 'Obtén 100% en un quiz completo (mínimo 5 preguntas)',
      icon: '🎯',
      condition: (stats) => stats.perfectQuizzes >= 1,
    },
    {
      id: 'xp_500',
      name: 'Acumulador',
      desc: 'Acumula 500 XP en total',
      icon: '💫',
      condition: (stats) => stats.totalXP >= 500,
    },
    {
      id: 'quiz_25',
      name: 'Imparable',
      desc: 'Completa 25 quizzes',
      icon: '🚀',
      condition: (stats) => stats.totalQuizzes >= 25,
    },
  ],

  /* ─── USUARIOS DEMO (Ranking) ─── */
  demoUsers: [
    { name: 'Valentina R.', avatar: '👩‍💻', xp: 4850, level: 6, streak: 12 },
    { name: 'Mateo A.',     avatar: '👨‍🔬', xp: 3920, level: 5, streak: 8 },
    { name: 'Sofía L.',     avatar: '👩‍🎓', xp: 3100, level: 5, streak: 5 },
    { name: 'Sebastián M.', avatar: '🧑‍💻', xp: 2780, level: 4, streak: 15 },
    { name: 'Camila T.',    avatar: '👩‍🏫', xp: 2340, level: 4, streak: 3 },
    { name: 'Diego P.',     avatar: '🧑‍🔬', xp: 1980, level: 3, streak: 7 },
    { name: 'Isabella F.',  avatar: '👩‍🎨', xp: 1560, level: 3, streak: 2 },
    { name: 'Andrés C.',    avatar: '🧑‍🎓', xp: 1120, level: 2, streak: 4 },
    { name: 'Lucía M.',     avatar: '👩‍💼', xp:  750, level: 2, streak: 1 },
    { name: 'Juan K.',      avatar: '🧑‍🏫', xp:  320, level: 1, streak: 0 },
  ],

  /* ─── AVATARES ─── */
  avatars: ['🧑‍💻', '👩‍💻', '🧑‍🔬', '👩‍🔬', '🧑‍🎓', '👩‍🎓', '🧑‍🏫', '👩‍🏫', '🧑‍🎨', '👩‍🎨'],
};

// Exportar globalmente
window.EQ_DATA = EQ_DATA;
